export interface Consulta {
  id: number,
  numeroHistoria: number,
  medico: number,
  motivoConsulta: string,
  apetito: string,
  orina: string,
  deposiciones: string,
  examenFisico: string,
  diagnostico: string,
  tratamiento: string,
  proximaCita: string,
  fechaCreacion:string,
  triaje: number,
}
