export interface Historial {
	id: number,
	numeroHistoria: number,
	dni: string,
	nombres: string,
	apellido_paterno: string,
	apellido_materno: string,
	sexo: string,
	edad: number,
	foto: null,
	fechaNac: String,
	celular: number,
	telefono: number,
	estadoCivil: number,
	gradoInstruccion: string,
	ocupacion: string,
	direccion: string,
	nacionalidad: string,
	email: string,
	estReg: boolean,
	distrito: number,
	provincia: number,
	departamento: number,
	fechaReg:String,
}